name: Greet
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - name: Hello World
        id: hello
        uses: skpatel-88/sandeep-hello-action@v1
        with:
          who-to-greet: 'Sandeep'
      
      - name: Get the output
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"
